# from root dir /is213-microservice-sms/
version: "3.8"

# necessary for the rabbitmq message broker
volumes:
  rabbitmq_data:

services:
  # rabbitmq message broker
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  # amqp worker -- sms
  amqpWorker:
    build:
      context: ./
      dockerfile: src/amqp/sms.Dockerfile
    image: ranonsew/amqpworker:test2
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
    restart: always

  # python test server
  amqpTestServer:
    build:
      context: ./
      dockerfile: src/amqp/amqpTest.Dockerfile
    image: ranonsew/amqptestserver:test2
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
    ports:
      - "47170:5101"
    restart: always